name: TPA
main: com.lith.tpa.Plugin

version: 0.0.1
api-version: 1.20

description: A MineCraft plugin for TPA
author: Lith
website: https://github.com/ImLith/MC-Tpa

depend: [LithCore, Redis]
softdepend: []

commands:
  tpa:
    description: Request teleport to another player.
    usage: /<command> <player>
    permission: tpa.tpa

  tpaccept:
    description: Accept player teleportation request
    usage: /<command> <player>
    permission: tpa.tpa

permissions:
  tpa.tpa:
    description: Use the /tpa command
    default: op
